// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbm_cIpdWPe5q2e0tHtPcSeHlot-DAm3c',
    appId: '1:144788227168:web:26c26fd71a66467d5d6f05',
    messagingSenderId: '144788227168',
    projectId: 'roadguard-a1f3b',
    authDomain: 'roadguard-a1f3b.firebaseapp.com',
    storageBucket: 'roadguard-a1f3b.firebasestorage.app',
    measurementId: 'G-CTT25GZNRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn82VbSd1qzKdeK9n0WZYXnYzA1hNFEC0',
    appId: '1:144788227168:android:2f39fc1458bffced5d6f05',
    messagingSenderId: '144788227168',
    projectId: 'roadguard-a1f3b',
    storageBucket: 'roadguard-a1f3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlViuK-aY_lTE399A0nex6vCNRise9Hz0',
    appId: '1:144788227168:ios:7e4048dbb6efe4775d6f05',
    messagingSenderId: '144788227168',
    projectId: 'roadguard-a1f3b',
    storageBucket: 'roadguard-a1f3b.firebasestorage.app',
    iosBundleId: 'com.example.roadguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlViuK-aY_lTE399A0nex6vCNRise9Hz0',
    appId: '1:144788227168:ios:7e4048dbb6efe4775d6f05',
    messagingSenderId: '144788227168',
    projectId: 'roadguard-a1f3b',
    storageBucket: 'roadguard-a1f3b.firebasestorage.app',
    iosBundleId: 'com.example.roadguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbm_cIpdWPe5q2e0tHtPcSeHlot-DAm3c',
    appId: '1:144788227168:web:80876f08b01421345d6f05',
    messagingSenderId: '144788227168',
    projectId: 'roadguard-a1f3b',
    authDomain: 'roadguard-a1f3b.firebaseapp.com',
    storageBucket: 'roadguard-a1f3b.firebasestorage.app',
    measurementId: 'G-T1ZJRWY2VL',
  );

}